### ISSUE TITLE
Polite Request

### ISSUE THREAD

**Issue by baconpaul** [airwindows/airwindows#17]
Hi

AirWindows is MIT licensed and I know that means we can use the source in any context we want, but it is still sociable to ask.

I was looking at the plugs today and we were chatting over in surge synth land. I'm debating making some of your algos available as Surge FX plugins. (Surge is GPL3 so it can link MIT code no problem). I know how to do this - your code structure is so uniform that it would be pretty easy to be honest (and thanks for that!)

But before I go ahead and do that, I wanted to ask if you would be OK with that and so on.

So if I did take a copy of your code, bind it under surge, and then had a Surge FX builtin called "air windows" where one param was an also picker and so on, and the rest were 'built in' fx which could interact with the surge modulation path would you mind? This would deploy into our VI, our FX bank, and eventually, into our Rack plugins.

But I long ago learned open source licensing has two parts. The legalities (so: of course I can do this, it's MIT licensed) and the niceties (but I don't want to make you upset). So figured I would ask.

Any thoughts?

Thanks!

**Comment by airwindows** [comment]
Sounds fine, go ahead. Note that the name of the company is 'Airwindows' (not BiCapital, not two words) and I did indeed choose MIT license on purpose. If anything, you will then be in trouble keeping up with my new work, but you're welcome to try and I do keep things very consistent so that should help.

Have fun and be sure to mention that you are using Airwindows open source code! And if you alter the stuff, you should say you are 'based on', or run the alterations by me as there might be a reason I'm doing it that way. I've had a guy trying to respond to a request to not have the bass distort… on SubsOnly in Monitoring. And of course that is a mix check thing calibrated so that you should balance the bass with everything else, and I preferred that it stay the way I had calibrated it: it was rather like asking that the peak clip light not light up anymore, on a meter. But the guy in question could have changed it, I would just prefer that he not call a changed version 'Airwindows Monitoring' if he had changed how it worked. 'Based on' would be fine for stuff where the tone or behavior thing is intentionally changed around :)

**Comment by baconpaul** [comment]
Great thanks.

Yes the uniformity makes it super easy. I actually got it working this morning. We don't think all of your plugs are appropriate for the surge signal path (and they are available as plugs anyway) but some are very very interesting.

And yes we will definitely mention that we are using your code in appropriate and prominent fashion.

And thanks for also writing and maintaining open source audio code!

Let me close this issue now but I'll drop a note here if/when we get something shippable.

**Comment by Jacky-Ligon** [comment]
Many thanks Airwindows, Chris, for permitting the use of your excellent open-source plugin code in Surge. 

There are many Airwindows fans in the SST project, and it's greatly expanded the possibilities for sound-design having a selection of your plugins in the FX section.

**Comment by airwindows** [comment]
Good. Rock on :) glad it's working for you, keep on keepin' on :)
