### ISSUE TITLE
Dyno possible optimization

### ISSUE THREAD

**Issue by NeverKnewTheName** [airwindows/airwindows#42]
the line `double dyno = pow(fabs(inputSampleL),4);` could be simplified to `dyno=pow( inputSampleL, 4)`
the same applies to the right channel. sth. to the power of an even number is always positive.

**Comment by airwindows** [comment]
For what it's worth I'm paying attention and making note of any changes that seem like I should find time to fit in the revision. It will always involve updating EVERY build subject to the bug like retro and modern Mac AU and VST, the WIndows builds, both Linux builds (intel and Raspberry Pi) and if there is a change in sound (even if the sound is due to a full-on bug and working not as intended) I'll need to do a new version so that saved mixes with the busted plugin don't change upon recall later :)
